sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_3d1850c14198_key -iv $encrypted_3d1850c14198_iv -in service-account-complexk8s-travis-deployer.json.enc -out ~\/Downloads/service-account-complexk8s-travis-deployer.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
